<?php
/**
 * @var \ExampleCorp\Learning\Block\Widget\Test $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<h3>
    <?= $escaper->escapeHtml($block->getData('title')) ?>
</h3>
<?php
/**
 * @var array $pages
 */
?>
<?php $pages = $block->getRightPages() ?>
<ul>
    <?php foreach ($pages as $page): ?>
    <li>
        <a href="<?= $escaper->escapeHtml($page['identifier']) ?>">
            <?= $escaper->escapeHtml($page['title']) ?>
        </a>
    </li>
    <?php endforeach; ?>
</ul>
