<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$buttonTitle = __('Add to Cart');

$_product = $block->getProduct();
$stockItem = $_product->getExtensionAttributes()->getStockItem();
$inStock = $stockItem->getQty() > 0;
$stockQuantity = $stockItem->getQty();

?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <div class="control" id="qty-counter" data-bind="scope:'quantityChanger'">
                <!-- ko template: getTemplate() --><!-- /ko -->
                <?php if ($inStock): ?>
                    <span class="check-image"></span>
                    <span class="stock-state-text">
                        <?= __('In Stock') ?>
                    </span>
                    <span class="quantity-count-text">
                        <?= $block->escapeHtml($stockQuantity) ?> <?= __('Items available') ?>
                    </span>
                <?php else: ?>
                    <span class="stock-state-text">
                        <?= __('Out of Stock') ?>
                    </span>
                <?php endif; ?>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script type="text/x-magento-init">
    {
        "#qty-counter": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "quantityChanger": {
                        "component": "Magento_Catalog/js/quantity_counter",
                        "template": "Magento_Catalog/quantity-template"
                    }
                }
            }
        }
    }
</script>
