<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$stockState = $objectManager->get(\Magento\CatalogInventory\Api\StockStateInterface::class);

// Get the product ID
$_product = $block->getProduct();
$productId = $_product->getId();

// Check if the product is in stock
$isInStock = $stockState->getStockQty($productId) > 0;
$stockQuantity = $stockState->getStockQty($productId);

/*
if ($isInStock) {
    echo "In Stock";
} else {
    echo "Out of Stock";
}
*/

//$_product = $block->getProduct();
?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <div class="control">
                <input type="button"
                       class="add-decrease-buttons decrease-button"/>
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                <input type="button"
                       class="add-decrease-buttons add-button"/>
                <?php if ($isInStock): ?>
                    <span>In Stock</span>
                    <span><?= $block->escapeHtml($stockQuantity) ?> items available</span>
                <?php else: ?>
                    <span>Out of Stock</span>
                <?php endif; ?>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
