<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct();

    $extendedClass = $block->getData('attributes_extended');
    $description = $extendedClass->getDescription($_product);
?>
<?php if ($_additional = $extendedClass->getAttributeList($_product)) :?>
    <div class="additional-attributes-wrapper table-wrapper">
        <table class="data table additional-attributes" id="product-attribute-specs-table">
            <tbody>
            <?php foreach ($_additional as $_data) :?>
                <tr>
                    <td class="col data bullet" >
                        <b> <?= $block->escapeHtml($_data['label'] . ': ') ?> </b>
                        <?= /* @noEscape */ $_helper->productAttribute($_product, $_data['value'], $_data['label']) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
                <tr>
                    <td class="col data" id="short-description">
                        <?= $block->escapeHtml($description) ?>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
<?php endif;?>



